# Sentiment Analysis Project - Fake Review dataset

In [1]:
import nltk
import warnings
warnings.filterwarnings('ignore')
import pandas as pd

# Step 1 - LOAD DATASET

In [2]:
df=pd.read_csv("C:/Users/sunil/Downloads/Fake Reviews datasets.csv")
df

,category,rating,label,reviews
0,Home_and_Kitchen_5,5,CG,"Love this! Well made, sturdy, and very comfor..."
1,Home_and_Kitchen_5,5,CG,"love it, a great upgrade from the original. I..."
2,Home_and_Kitchen_5,5,CG,This pillow saved my back. I love the look and...
3,Home_and_Kitchen_5,1,CG,"Missing information on how to use it, but it i..."
4,Home_and_Kitchen_5,5,CG,Very nice set. Good quality. We have had the s...
...,...,...,...,...
40427,Clothing_Shoes_and_Jewelry_5,4,OR,I had read some reviews saying that this bra r...
40428,Clothing_Shoes_and_Jewelry_5,5,CG,I wasn't sure exactly what it would be. It is ...
40429,Clothing_Shoes_and_Jewelry_5,2,OR,"You can wear the hood by itself, wear it with ..."
40430,Clothing_Shoes_and_Jewelry_5,1,CG,I liked nothing about this dress. The only rea...
40431,Clothing_Shoes_and_Jewelry_5,5,OR,I work in the wedding industry and have to wor...

# Step 2 - SEPARATE WANTED COLUMN

In [3]:
df1=df[['reviews']]
df1.head()

                                             reviews
0  Love this!  Well made, sturdy, and very comfor...
1  love it, a great upgrade from the original.  I...
2  This pillow saved my back. I love the look and...
3  Missing information on how to use it, but it i...
4  Very nice set. Good quality. We have had the s...

# Step 3 - CLEANING

In [4]:
import re
def clean(text):
    text = re.sub('[^A-Za-z]+', ' ', text)
    return text

df1['Cleaned Reviews'] = df1['reviews'].apply(clean)
df1.head()

,reviews,Cleaned Reviews
0,"Love this! Well made, sturdy, and very comfor...",Love this Well made sturdy and very comfortabl...
1,"love it, a great upgrade from the original. I...",love it a great upgrade from the original I ve...
2,This pillow saved my back. I love the look and...,This pillow saved my back I love the look and ...
3,"Missing information on how to use it, but it i...",Missing information on how to use it but it is...
4,Very nice set. Good quality. We have had the s...,Very nice set Good quality We have had the set...

# Step 4 - LOWERCASE

In [6]:
df1['Lowercase'] = df1['Cleaned Reviews'].apply(lambda x: " ".join(word.lower() for word in x.split()))
df1.head()

,reviews,Cleaned Reviews,Lowercase
0,"Love this! Well made, sturdy, and very comfor...",Love this Well made sturdy and very comfortabl...,love this well made sturdy and very comfortabl...
1,"love it, a great upgrade from the original. I...",love it a great upgrade from the original I ve...,love it a great upgrade from the original i ve...
2,This pillow saved my back. I love the look and...,This pillow saved my back I love the look and ...,this pillow saved my back i love the look and ...
3,"Missing information on how to use it, but it i...",Missing information on how to use it but it is...,missing information on how to use it but it is...
4,Very nice set. Good quality. We have had the s...,Very nice set Good quality We have had the set...,very nice set good quality we have had the set...

# Step 5 - STOPWORDS

In [7]:
from nltk.corpus import stopwords
stop_words = stopwords.words('english')
stop_words.remove("no")
stop_words.remove("not")
print(stop_words)

['a', 'about', 'above', 'after', 'again', 'against', 'ain', 'all', 'am', 'an', 'and', 'any', 'are', 'aren', "aren't", 'as', 'at', 'be', 'because', 'been', 'before', 'being', 'below', 'between', 'both', 'but', 'by', 'can', 'couldn', "couldn't", 'd', 'did', 'didn', "didn't", 'do', 'does', 'doesn', "doesn't", 'doing', 'don', "don't", 'down', 'during', 'each', 'few', 'for', 'from', 'further', 'had', 'hadn', "hadn't", 'has', 'hasn', "hasn't", 'have', 'haven', "haven't", 'having', 'he', "he'd", "he'll", 'her', 'here', 'hers', 'herself', "he's", 'him', 'himself', 'his', 'how', 'i', "i'd", 'if', "i'll", "i'm", 'in', 'into', 'is', 'isn', "isn't", 'it', "it'd", "it'll", "it's", 'its', 'itself', "i've", 'just', 'll', 'm', 'ma', 'me', 'mightn', "mightn't", 'more', 'most', 'mustn', "mustn't", 'my', 'myself', 'needn', "needn't", 'nor', 'now', 'o', 'of', 'off', 'on', 'once', 'only', 'or', 'other', 'our', 'ours', 'ourselves', 'out', 'over', 'own', 're', 's', 'same', 'shan', "shan't", 'she', "she'd", "she'll", "she's", 'should', 'shouldn', "shouldn't", "should've", 'so', 'some', 'such', 't', 'than', 'that', "that'll", 'the', 'their', 'theirs', 'them', 'themselves', 'then', 'there', 'these', 'they', "they'd", "they'll", "they're", "they've", 'this', 'those', 'through', 'to', 'too', 'under', 'until', 'up', 've', 'very', 'was', 'wasn', "wasn't", 'we', "we'd", "we'll", "we're", 'were', 'weren', "weren't", "we've", 'what', 'when', 'where', 'which', 'while', 'who', 'whom', 'why', 'will', 'with', 'won', "won't", 'wouldn', "wouldn't", 'y', 'you', "you'd", "you'll", 'your', "you're", 'yours', 'yourself', 'yourselves', "you've"]

In [8]:
df1['stopwords'] = df1['Lowercase'].apply(lambda x: " ".join(word for word in x.split() if word not in stop_words))
df1.head()

,reviews,Cleaned Reviews,Lowercase,stopwords
0,"Love this! Well made, sturdy, and very comfor...",Love this Well made sturdy and very comfortabl...,love this well made sturdy and very comfortabl...,love well made sturdy comfortable love pretty
1,"love it, a great upgrade from the original. I...",love it a great upgrade from the original I ve...,love it a great upgrade from the original i ve...,love great upgrade original mine couple years
2,This pillow saved my back. I love the look and...,This pillow saved my back I love the look and ...,this pillow saved my back i love the look and ...,pillow saved back love look feel pillow
3,"Missing information on how to use it, but it i...",Missing information on how to use it but it is...,missing information on how to use it but it is...,missing information use great product price
4,Very nice set. Good quality. We have had the s...,Very nice set Good quality We have had the set...,very nice set good quality we have had the set...,nice set good quality set two months not

# Step 6 - TOKENIZATION AND POS

In [9]:
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import wordnet
from nltk import pos_tag

# Download necessary NLTK data files
nltk.download('punkt')
nltk.download('wordnet')    #WordNet is a large lexical database of English 

# POS tagger dictionary
pos_dict = {'J': wordnet.ADJ, 'V': wordnet.VERB, 'N': wordnet.NOUN, 'R': wordnet.ADV}

def token_pos(text):
    return [
        (word, pos_dict.get(tag[0]))
        for word, tag in pos_tag(word_tokenize(text))
    ]

# Apply to your data
df1['POS tagged'] = df1['stopwords'].apply(token_pos)

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\sunil\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\sunil\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

In [10]:
df1.head()

,reviews,Cleaned Reviews,Lowercase,stopwords,POS tagged
0,"Love this! Well made, sturdy, and very comfor...",Love this Well made sturdy and very comfortabl...,love this well made sturdy and very comfortabl...,love well made sturdy comfortable love pretty,"[(love, n), (well, r), (made, v), (sturdy, a),..."
1,"love it, a great upgrade from the original. I...",love it a great upgrade from the original I ve...,love it a great upgrade from the original i ve...,love great upgrade original mine couple years,"[(love, r), (great, a), (upgrade, a), (origina..."
2,This pillow saved my back. I love the look and...,This pillow saved my back I love the look and ...,this pillow saved my back i love the look and ...,pillow saved back love look feel pillow,"[(pillow, n), (saved, v), (back, r), (love, a)..."
3,"Missing information on how to use it, but it i...",Missing information on how to use it but it is...,missing information on how to use it but it is...,missing information use great product price,"[(missing, v), (information, n), (use, n), (gr..."
4,Very nice set. Good quality. We have had the s...,Very nice set Good quality We have had the set...,very nice set good quality we have had the set...,nice set good quality set two months not,"[(nice, a), (set, v), (good, a), (quality, n),..."

# Step 7 - LEMMA

In [11]:
from nltk.stem import WordNetLemmatizer

# Initialize the lemmatizer
wordnet_lemmatizer = WordNetLemmatizer()

def lemmatize(pos_data):
    ans = " "
    for word, pos in pos_data:
        if not pos:  # If no POS tag is available, use the word as is
            lemma = word
        else:
            # Lemmatize based on the POS tag
            lemma = wordnet_lemmatizer.lemmatize(word, pos=pos)
        ans = ans + " " + lemma  # Add the lemma to the result string
    return ans

# Assuming df2 is your dataframe and 'POS tagged' contains POS-tagged text
df1['Lemma'] = df1['POS tagged'].apply(lemmatize)

In [12]:
df1.head()

,reviews,Cleaned Reviews,Lowercase,stopwords,POS tagged,Lemma
0,"Love this! Well made, sturdy, and very comfor...",Love this Well made sturdy and very comfortabl...,love this well made sturdy and very comfortabl...,love well made sturdy comfortable love pretty,"[(love, n), (well, r), (made, v), (sturdy, a),...",love well make sturdy comfortable love pretty
1,"love it, a great upgrade from the original. I...",love it a great upgrade from the original I ve...,love it a great upgrade from the original i ve...,love great upgrade original mine couple years,"[(love, r), (great, a), (upgrade, a), (origina...",love great upgrade original mine couple year
2,This pillow saved my back. I love the look and...,This pillow saved my back I love the look and ...,this pillow saved my back i love the look and ...,pillow saved back love look feel pillow,"[(pillow, n), (saved, v), (back, r), (love, a)...",pillow save back love look feel pillow
3,"Missing information on how to use it, but it i...",Missing information on how to use it but it is...,missing information on how to use it but it is...,missing information use great product price,"[(missing, v), (information, n), (use, n), (gr...",miss information use great product price
4,Very nice set. Good quality. We have had the s...,Very nice set Good quality We have had the set...,very nice set good quality we have had the set...,nice set good quality set two months not,"[(nice, a), (set, v), (good, a), (quality, n),...",nice set good quality set two month not

# Step 7 - ASSIGN SCORES FOR TESTING

In [13]:
def scores(RATES):
    if RATES > 3:  # Positive threshold
        return 0   # positive
    elif RATES < 3:  # Negative threshold
        return 1 # negative
    else:
        return 2 # neutral
df["scores"]=df["rating"].apply(scores)

# Step 8 - SEPARATE X AND Y

In [14]:
x=df1['Lemma']
y=df['scores']

In [15]:
print(len(x))
print(len(y))

40432
40432

# Step 9 - TRAIN TEST SPLIT

In [16]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

# Step 10 - VECTORIZATION

In [17]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()
x_train_vec = tfidf.fit_transform(x_train)
x_test_vec = tfidf.transform(x_test)

# Step 11 - MODEL

In [18]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score
model = MultinomialNB()
model.fit(x_train_vec, y_train)
y_pred = model.predict(x_test_vec)
print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.8056139483121059